version: 2.1
orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-cli: circleci/aws-cli@2.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install angularcli
          command: npm run angular-cli:install
      - run:
          name: Angular Install
          command: cd ./client && npm install
      - run:
          name: API Install
          command: cd ./server && npm install
      - run:
          name: Angular Build
          command: cd ./client && npm run build
      - run:
          name: API Build
          command: cd ./server && npm run build
      - run:
          name: API Pre Deployment
          command: cd ./server && eb init --platform 'Node.js 14 running on 64bit Amazon Linux 2' --region 'us-east-1' 'storefront-backend-api'
      - run:
          name: API  Deployment
          command: cd ./server && eb deploy
      - run:
          name: Angular Deployment
          command: cd ./client &&  aws s3 cp --recursive --acl public-read ./dist s3://storefront-frontend/