version: 2.1
orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-cli: circleci/aws-cli@2.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install angularcli
          command: npm run angular-cli:install
      - run:
          name: Angular Install
          command: npm run angular:install
      - run:
          name: API Install
          command: npm run api:install
      - run:
          name: Angular Build
          command: npm run angular:build
      - run:
          name: API Build
          command: npm run api:build
      - run:
          name: API Pre Deployment
          command: npm run pre:deploy
      - run:
          name: API  Deployment
          command: npm run api:deploy
      - run:
          name: Angular Deployment
          command: npm run angular:deploy